version: '3.7'
services:
  frontend:
    build:
      context: ~/UWERX/
      dockerfile: Dockerfile.frontend  # Use the Node.js Dockerfile
    container_name: frontend
    command: npm start
    ports:
      - "3000:3000"  # Node.js application port (HTTP)

  backend:
    build:
      context: ~/UWERX-back-end-nest/
      dockerfile: Dockerfile.backend
    container_name: backend
    command: npm start
    ports:
      - "3001:3001"


  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Nginx Dockerfile
    container_name: nginx-proxy
    ports:
      - "443:443"  # Nginx SSL port (HTTPS)
      - "80:80"    # Nginx HTTP port
    depends_on:
      - frontend
      - backend
